/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Trip */
        post: operations["create_trip_api_trips_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{trip_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trip */
        get: operations["get_trip_api_trips__trip_id__get"];
        put?: never;
        post?: never;
        /** Delete Trip */
        delete: operations["delete_trip_api_trips__trip_id__delete"];
        options?: never;
        head?: never;
        /** Patch Trip */
        patch: operations["patch_trip_api_trips__trip_id__patch"];
        trace?: never;
    };
    "/api/trips/{trip_id}/days/{day_index}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Item */
        post: operations["add_item_api_trips__trip_id__days__day_index__items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{trip_id}/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Item */
        delete: operations["remove_item_api_trips__trip_id__items__item_id__delete"];
        options?: never;
        head?: never;
        /** Patch Item */
        patch: operations["patch_item_api_trips__trip_id__items__item_id__patch"];
        trace?: never;
    };
    "/api/trips/{trip_id}/days/{day_index}/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Reorder */
        put: operations["reorder_api_trips__trip_id__days__day_index__order_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{trip_id}/days/{day_index}/optimize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Optimize Day
         * @description FR-8 — 순서 최적화. 캐시가 적중하면 외부 호출 없이 끝난다 (BR-29).
         */
        post: operations["optimize_day_api_trips__trip_id__days__day_index__optimize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{trip_id}/items/{item_id}/opening-hours": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set Opening Hours
         * @description BR-35 — 영업시간은 **여기서만** 채워진다. 외부 API·LLM 경로는 없다.
         */
        put: operations["set_opening_hours_api_trips__trip_id__items__item_id__opening_hours_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{trip_id}/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Generation
         * @description 일정 생성을 시작하고 **즉시** job_id 를 반환한다.
         *
         *     NFR-1 — 최대 60초가 걸리므로 HTTP 응답을 붙잡지 않는다.
         */
        post: operations["start_generation_api_trips__trip_id__generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job
         * @description 진행 상태 폴링 (WF-2 6단계).
         *
         *     `partial` 은 실패가 아니라 품질 저하다 (DD-23). 프론트는 이를 구체적으로
         *     알려야 한다 — "3곳을 찾지 못했습니다", "이동시간이 추정치입니다".
         */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/places/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Places
         * @description FR-6 — 지역검색은 1회 5건이 상한이라 `page` 로 이어 받는다 (CON-2).
         */
        get: operations["search_places_api_places_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/places/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Place Content
         * @description FR-20·21 — 추천 콘텐츠.
         *
         *     BR-40 — 근거 블로그가 3건 미만이면 `highlights` 는 빈 목록이다.
         */
        get: operations["place_content_api_places_content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/places/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Suggestions
         * @description FR-22 — 주변 미포함 추천. 이미 담긴 장소는 제외한다.
         */
        get: operations["suggestions_api_places_suggestions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{trip_id}/share": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Issue Share Token
         * @description BR-36 — 암호학적 난수 43자. `trip_id` 와 수학적 관계가 없다.
         */
        post: operations["issue_share_token_api_trips__trip_id__share_post"];
        /**
         * Revoke Share Token
         * @description BR-38 — 폐기 시 기존 링크가 즉시 무효화된다.
         */
        delete: operations["revoke_share_token_api_trips__trip_id__share_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shared/{share_token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Shared Trip
         * @description BR-37 — 편집 연산이 정의되지 않은 타입을 반환한다.
         *
         *     응답에 `share_token` 을 포함하지 않는다 — 열람자가 토큰을 재발급·폐기할
         *     권한이 없기 때문이다.
         */
        get: operations["get_shared_trip_api_shared__share_token__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{trip_id}/export.ics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Ics
         * @description 일정을 iCalendar 로 내보낸다.
         *
         *     BR-46 — `travel_mode`·`warnings`·`category`·`phone` 은 VEVENT 표준 필드가
         *     없어 손실된다(X- 속성으로만 내보내고 되읽지 않는다).
         */
        get: operations["export_ics_api_trips__trip_id__export_ics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Runtime Config
         * @description 프론트가 부팅 시 1회 조회하는 런타임 설정 (WBR-32).
         *
         *     외부 API 를 호출하지 않으므로 쿼터를 소모하지 않는다.
         */
        get: operations["get_runtime_config_api_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness
         * @description 프로세스 응답 여부만 확인한다. Docker 헬스체크 대상 (ID-13).
         */
        get: operations["liveness_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness
         * @description DB 접근 + 목 모드 현황 + 쿼터 + 서킷 상태.
         *
         *     FR-33 — 프론트는 `modes` 를 보고 "데모 데이터" 배너를 띄운다.
         */
        get: operations["readiness_api_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BlogRefOut */
        BlogRefOut: {
            /** Title */
            title: string;
            /** Link */
            link: string;
            /** Blogger Name */
            blogger_name?: string | null;
            /** Post Date */
            post_date?: string | null;
        };
        /**
         * BudgetLevel
         * @enum {string}
         */
        BudgetLevel: "LOW" | "MEDIUM" | "HIGH";
        /** CoordinateOut */
        CoordinateOut: {
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
        };
        /**
         * DayRuleIn
         * @description FR-13 — **사용자 입력 영업시간** (BR-35). 외부에서 채우는 경로는 없다.
         */
        DayRuleIn: {
            /** Weekday */
            weekday: number;
            /** Open */
            open?: string | null;
            /** Close */
            close?: string | null;
            /**
             * Closed
             * @default false
             */
            closed: boolean;
        };
        /** DayRuleOut */
        DayRuleOut: {
            /** Weekday */
            weekday: number;
            /** Open */
            open?: string | null;
            /** Close */
            close?: string | null;
            /**
             * Closed
             * @default false
             */
            closed: boolean;
        };
        /**
         * GenerationStep
         * @enum {string}
         */
        GenerationStep: "DRAFTING" | "RESOLVING" | "ROUTING" | "OPTIMIZING" | "SCHEDULING" | "SAVING";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** ImageRefOut */
        ImageRefOut: {
            /** Thumbnail Url */
            thumbnail_url: string;
            /** Link */
            link: string;
            /**
             * Source Title
             * @default
             */
            source_title: string;
        };
        /**
         * ItemCreate
         * @description FR-5 — 검색 결과에서 항목 추가.
         */
        ItemCreate: {
            /** Name */
            name: string;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Category Raw */
            category_raw?: string | null;
            /** Road Address */
            road_address?: string | null;
            /** Address */
            address?: string | null;
            /** Phone */
            phone?: string | null;
            /** Stay Minutes */
            stay_minutes?: number | null;
            /** Memo */
            memo?: string | null;
        };
        /**
         * ItemPatch
         * @description FR-7, FR-11 — 항목 편집.
         */
        ItemPatch: {
            /** Stay Minutes */
            stay_minutes?: number | null;
            /** Memo */
            memo?: string | null;
            travel_mode?: components["schemas"]["TravelMode"] | null;
            /** Time Fixed */
            time_fixed?: boolean | null;
            /** Fixed Time */
            fixed_time?: string | null;
        };
        /** ItemWarningOut */
        ItemWarningOut: {
            type: components["schemas"]["WarningType"];
            /** Detail */
            detail: string;
        };
        /** ItineraryItemOut */
        ItineraryItemOut: {
            /** Item Id */
            item_id: string;
            place: components["schemas"]["PlaceOut"];
            /** Stay Minutes */
            stay_minutes: number;
            /** Position */
            position: number;
            /** Arrival At */
            arrival_at?: string | null;
            /** Departure At */
            departure_at?: string | null;
            /**
             * Time Fixed
             * @default false
             */
            time_fixed: boolean;
            /** Fixed Time */
            fixed_time?: string | null;
            travel_mode?: components["schemas"]["TravelMode"] | null;
            /** Memo */
            memo?: string | null;
            /**
             * Warnings
             * @default []
             */
            warnings: components["schemas"]["ItemWarningOut"][];
        };
        /** JobAccepted */
        JobAccepted: {
            /** Job Id */
            job_id: string;
            /** Trip Id */
            trip_id: string;
            /**
             * State
             * @constant
             */
            state: "queued";
        };
        /**
         * JobState
         * @enum {string}
         */
        JobState: "queued" | "running" | "succeeded" | "partial" | "failed";
        /** JobStatusOut */
        JobStatusOut: {
            /** Job Id */
            job_id: string;
            /** Trip Id */
            trip_id: string;
            state: components["schemas"]["JobState"];
            step?: components["schemas"]["GenerationStep"] | null;
            /** Progress */
            progress: number;
            /** Resolved Count */
            resolved_count: number;
            /** Unresolved Count */
            unresolved_count: number;
            /** Problem */
            problem?: Record<string, never> | null;
        };
        /**
         * LimitsOut
         * @description 폼 검증 상한. 프론트가 숫자를 하드코딩하지 않도록 서버가 내려준다 (WBR-10).
         */
        LimitsOut: {
            /** Max Trip Days */
            max_trip_days: number;
            /** Max Items Per Day */
            max_items_per_day: number;
            /** Max Items Per Trip */
            max_items_per_trip: number;
        };
        /** OpeningHoursIn */
        OpeningHoursIn: {
            /** Weekday Rules */
            weekday_rules: components["schemas"]["DayRuleIn"][];
        };
        /**
         * OpeningHoursOut
         * @description BR-35 — 사용자가 입력한 경우에만 존재한다(대개 `null`).
         */
        OpeningHoursOut: {
            /**
             * Weekday Rules
             * @default []
             */
            weekday_rules: components["schemas"]["DayRuleOut"][];
            /**
             * Entered By User
             * @default true
             */
            entered_by_user: boolean;
        };
        /**
         * OptimizeIn
         * @description FR-8 — 순서 최적화 제약 (BR-19).
         */
        OptimizeIn: {
            /** Anchor Start */
            anchor_start?: string | null;
            /** Anchor End */
            anchor_end?: string | null;
        };
        /** PagedPlacesOut */
        PagedPlacesOut: {
            /** Items */
            items: components["schemas"]["PlaceOut"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Has More */
            has_more: boolean;
        };
        /**
         * PlaceCategory
         * @enum {string}
         */
        PlaceCategory: "RESTAURANT" | "CAFE" | "ATTRACTION" | "MUSEUM" | "SHOPPING" | "ACCOMMODATION" | "OTHER";
        /**
         * PlaceContentOut
         * @description FR-20·21 / BR-40 — `sources` 가 3건 미만이면 `highlights` 는 반드시 빈 목록이다.
         */
        PlaceContentOut: {
            /** Place Id */
            place_id: string;
            /**
             * Highlights
             * @default []
             */
            highlights: string[];
            /**
             * Sources
             * @default []
             */
            sources: components["schemas"]["BlogRefOut"][];
            /**
             * Images
             * @default []
             */
            images: components["schemas"]["ImageRefOut"][];
            /**
             * Is Ai Summary
             * @default true
             */
            is_ai_summary: boolean;
        };
        /** PlaceOut */
        PlaceOut: {
            /** Place Id */
            place_id: string;
            /** Name */
            name: string;
            coordinate: components["schemas"]["CoordinateOut"];
            category: components["schemas"]["PlaceCategory"];
            /** Road Address */
            road_address?: string | null;
            /** Address */
            address?: string | null;
            /** Category Raw */
            category_raw?: string | null;
            /** Phone */
            phone?: string | null;
            /** Naver Link */
            naver_link?: string | null;
            source: components["schemas"]["PlaceSource"];
            /** Resolved From */
            resolved_from?: string | null;
            /** Match Score */
            match_score?: number | null;
            opening_hours?: components["schemas"]["OpeningHoursOut"] | null;
        };
        /**
         * PlaceSource
         * @enum {string}
         */
        PlaceSource: "NAVER_LOCAL" | "USER_MANUAL" | "MOCK";
        /** QuotaUsageOut */
        QuotaUsageOut: {
            /** Call Count */
            call_count: number;
            /** Error Count */
            error_count: number;
            /** Daily Limit */
            daily_limit?: number | null;
        };
        /**
         * ReadOnlyTripOut
         * @description BR-37 / DD-25 — 공유 조회 응답.
         *
         *     🔴 `share_token` 을 포함하지 않는다. 열람자는 토큰을 재발급·폐기할 권한이 없다.
         */
        ReadOnlyTripOut: {
            /** Trip Id */
            trip_id: string;
            /** Title */
            title: string;
            /** Destination */
            destination: string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /** Party Size */
            party_size: number;
            /**
             * Style Tags
             * @default []
             */
            style_tags: string[];
            /**
             * Day Start Time
             * Format: time
             */
            day_start_time: string;
            /**
             * Day End Time
             * Format: time
             */
            day_end_time: string;
            default_travel_mode: components["schemas"]["TravelMode"];
            budget_level?: components["schemas"]["BudgetLevel"] | null;
            /** Days */
            days: components["schemas"]["TripDayOut"][];
            /**
             * Read Only
             * @default true
             * @constant
             */
            read_only: true;
        };
        /** ReadinessOut */
        ReadinessOut: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Modes */
            modes: {
                [key: string]: string;
            };
            /** Quota */
            quota: {
                [key: string]: components["schemas"]["QuotaUsageOut"];
            };
            /** Circuits */
            circuits: {
                [key: string]: string;
            };
            /** Database */
            database: boolean;
            /** Map Client Key Configured */
            map_client_key_configured: boolean;
        };
        /** ReorderIn */
        ReorderIn: {
            /** Item Ids */
            item_ids: string[];
        };
        /**
         * ResolveFailureCode
         * @enum {string}
         */
        ResolveFailureCode: "NO_SEARCH_RESULT" | "LOW_SIMILARITY" | "OUT_OF_REGION" | "CATEGORY_MISMATCH" | "INVALID_COORDINATE" | "SEARCH_UNAVAILABLE";
        /**
         * RuntimeConfigOut
         * @description 개정 A-1 — `GET /api/config` 응답.
         *
         *     🔴 **검색 API 키와 LLM 키는 절대 포함하지 않는다** (SEC-11).
         *     `map_client_key` 만 예외인데, 지도 SDK 특성상 브라우저에 노출될 수밖에 없고
         *     도메인 화이트리스트로 방어하기 때문이다 (CON-3).
         */
        RuntimeConfigOut: {
            /** Map Client Key */
            map_client_key: string | null;
            /** Modes */
            modes: {
                [key: string]: string;
            };
            limits: components["schemas"]["LimitsOut"];
        };
        /** ShareTokenOut */
        ShareTokenOut: {
            /** Share Token */
            share_token: string;
            /** Url */
            url: string;
        };
        /** SuggestionsOut */
        SuggestionsOut: {
            /** Items */
            items: components["schemas"]["PlaceOut"][];
        };
        /**
         * TravelMode
         * @enum {string}
         */
        TravelMode: "WALK" | "CAR" | "TRANSIT";
        /** TripDayOut */
        TripDayOut: {
            /** Day Index */
            day_index: number;
            /** Items */
            items: components["schemas"]["ItineraryItemOut"][];
        };
        /** TripMetaPatch */
        TripMetaPatch: {
            /** Title */
            title?: string | null;
        };
        /** TripOut */
        TripOut: {
            /** Trip Id */
            trip_id: string;
            /** Title */
            title: string;
            /** Destination */
            destination: string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /** Party Size */
            party_size: number;
            /**
             * Style Tags
             * @default []
             */
            style_tags: string[];
            /**
             * Day Start Time
             * Format: time
             */
            day_start_time: string;
            /**
             * Day End Time
             * Format: time
             */
            day_end_time: string;
            default_travel_mode: components["schemas"]["TravelMode"];
            budget_level?: components["schemas"]["BudgetLevel"] | null;
            /** Days */
            days: components["schemas"]["TripDayOut"][];
            /**
             * Unresolved
             * @default []
             */
            unresolved: components["schemas"]["UnresolvedOut"][];
            /** Share Token */
            share_token?: string | null;
        };
        /**
         * TripSpecIn
         * @description FR-1 — 여행 생성 입력.
         */
        TripSpecIn: {
            /** Title */
            title: string;
            /** Destination */
            destination: string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /**
             * Party Size
             * @default 2
             */
            party_size: number;
            /**
             * Style Tags
             * @default []
             */
            style_tags: string[];
            /**
             * Day Start Time
             * Format: time
             * @default 09:00:00
             */
            day_start_time: string;
            /**
             * Day End Time
             * Format: time
             * @default 21:00:00
             */
            day_end_time: string;
            /** @default TRANSIT */
            default_travel_mode: components["schemas"]["TravelMode"];
            budget_level?: components["schemas"]["BudgetLevel"] | null;
        };
        /**
         * UnresolvedOut
         * @description FR-3 / BR-18 — 일정에 들어가지 못한 후보. 프론트가 "확인 필요"로 노출한다.
         */
        UnresolvedOut: {
            /** Raw Name */
            raw_name: string;
            /** Day Index */
            day_index: number;
            /** Category Hint */
            category_hint?: string | null;
            /**
             * Reason
             * @default
             */
            reason: string;
            failure_code: components["schemas"]["ResolveFailureCode"];
            /** Best Candidate Name */
            best_candidate_name?: string | null;
            /** Best Match Score */
            best_match_score?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WarningType
         * @enum {string}
         */
        WarningType: "OUTSIDE_OPENING_HOURS" | "FIXED_TIME_CONFLICT" | "DAY_OVERFLOW" | "ESTIMATED_TRAVEL_TIME";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_trip_api_trips_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripSpecIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trip_api_trips__trip_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_trip_api_trips__trip_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_trip_api_trips__trip_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripMetaPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_item_api_trips__trip_id__days__day_index__items_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
                day_index: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_item_api_trips__trip_id__items__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_item_api_trips__trip_id__items__item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reorder_api_trips__trip_id__days__day_index__order_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
                day_index: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReorderIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    optimize_day_api_trips__trip_id__days__day_index__optimize_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
                day_index: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OptimizeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_opening_hours_api_trips__trip_id__items__item_id__opening_hours_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpeningHoursIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_generation_api_trips__trip_id__generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripSpecIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatusOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_places_api_places_search_get: {
        parameters: {
            query: {
                q: string;
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedPlacesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    place_content_api_places_content_get: {
        parameters: {
            query: {
                trip_id: string;
                item_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaceContentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    suggestions_api_places_suggestions_get: {
        parameters: {
            query: {
                trip_id: string;
                day_index: number;
                keyword?: string;
                radius?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestionsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    issue_share_token_api_trips__trip_id__share_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareTokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_share_token_api_trips__trip_id__share_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_shared_trip_api_shared__share_token__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                share_token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadOnlyTripOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_ics_api_trips__trip_id__export_ics_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_runtime_config_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeConfigOut"];
                };
            };
        };
    };
    liveness_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    readiness_api_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessOut"];
                };
            };
        };
    };
}
